### ISSUE TITLE
Button "Generate Slack API key"  doesn't work

### ISSUE THREAD

**Issue by sis032** [vivek-nexus/google-meet-slack-integration#16]
Hi. Please help me. The button "Generate Slack API key"  doesn't work.
![image](https://github.com/vivek-nexus/google-meet-slack-integration/assets/107427589/88b471a1-2a2f-4053-9c0b-4f9e79c3ed0b)
![image](https://github.com/vivek-nexus/google-meet-slack-integration/assets/107427589/77c14ab3-3d36-4124-89e5-477ed4bf5c8a)

**Comment by vivek-nexus** [comment]
The server had a small issue. It is fixed now and I've tested it. Please retry generating the API key.

**Comment by sis032** [comment]
All work. Thank you
